# Generated by Django 4.0.2 on 2022-02-13 07:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTaskScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание задачи')),
                ('duration', models.DurationField(blank=True, verbose_name='Ожидаемое время выполнения')),
                ('when', models.DateTimeField(blank=True)),
                ('importance', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=0)),
                ('image', models.ImageField(blank=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/scheduler_image/')),
                ('video', models.FileField(blank=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/scheduler_video/')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Тип задачи')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание типа задачи')),
                ('has_subtask', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название упражнения')),
                ('duration', models.DurationField(blank=True, verbose_name='Продолжительность')),
                ('count', models.PositiveIntegerField(blank=True)),
                ('timeout', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/training_image/')),
                ('video', models.FileField(blank=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/training_video/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/product/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='D:\\Dev\\task_scheduler\\extended_to_do\\task_scheduler\\back_media/video/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
