# Generated by Django 4.0.2 on 2022-02-17 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='scheduler.ProductRecipe', to='scheduler.Product'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='scheduler.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scheduler.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='maintaskscheduler',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='maintaskscheduler',
            name='scheduler_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scheduler', to='scheduler.schedulertype'),
        ),
    ]
