# Generated by Django 4.0.2 on 2022-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название магазина')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес магазина')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('household', 'Household')], default=0, max_length=200, verbose_name='Категория продукта'),
        ),
    ]
