# Generated by Django 4.0.2 on 2022-02-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productpurchase',
            name='purchase_user_product_unique',
        ),
    ]
