# Generated by Django 4.0.2 on 2022-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Продукты', 'Grocery'), ('Хозяйственные товары', 'Household')], default=0, max_length=200, verbose_name='Категория продукта'),
        ),
    ]
