# Generated by Django 4.0.2 on 2022-02-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_productpurchase_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpurchase',
            options={'ordering': ('-date_added',), 'verbose_name': 'покупку продуктов', 'verbose_name_plural': 'покупки продуктов'},
        ),
    ]
