# Generated by Django 4.0.2 on 2022-02-20 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_productpurchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Не менее 1')], verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
    ]
