# Generated by Django 4.0.2 on 2022-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('household', 'Household')], default=0, max_length=200, verbose_name='Категория продукта'),
        ),
    ]
