# Generated by Django 4.0.2 on 2022-02-20 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_productrecipe_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Не менее 1')], verbose_name='Количество продукта'),
        ),
    ]
