# Generated by Django 4.0.2 on 2022-02-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_productpurchase_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='purchase',
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='scheduler.productpurchase')),
                ('recepies_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='scheduler.purchase')),
            ],
        ),
    ]
