# Generated by Django 4.0.2 on 2022-02-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_remove_productpurchase_purchase_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
